title: Mika Pelvola  # You can add your name here

logo: profilepic.jpeg # Use a relative path to logo image 

description: About me # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
   # Add SEO plugin

email: youremail@gmail.com # Allow visitors to contact you
